server:
  port: 8080
  servlet:
    context-path: /course
spring:
  application:
    name: course
  #  数据库驱动
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course
    username: root
    password: root